name: CMake build

on: push

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest, macos-26]
    steps:
      - uses: actions/checkout@v4
      - uses: ossia/actions/avendish-template@avendish-template-action
        with:
          run-tests: 'true'
